import Link from "next/link";
import { ArrowRight, BookOpenCheck, ClipboardCheck, SearchCheck, ShieldCheck } from "lucide-react";
import { AdvisorTool } from "@/src/components/advisor-tool";
import styles from "./page.module.css";

const framework = [["Dừng lại", "Nhận diện mục tiêu, tác giả và điều AI đang khẳng định."], ["Tìm nguồn", "Ưu tiên nguồn gốc, cơ quan chuyên môn và tài liệu có ngày xuất bản."], ["Đối chiếu", "Tìm ít nhất một nguồn độc lập trước khi tin hoặc chia sẻ."], ["Lần về ngữ cảnh", "Đọc câu gốc, dữ liệu gốc và bối cảnh thay vì chỉ đọc trích dẫn."]];
const craap = [["C", "Currency", "Thông tin có còn mới không?"], ["R", "Relevance", "Có trả lời đúng câu hỏi không?"], ["A", "Authority", "Ai chịu trách nhiệm cho thông tin?"], ["A", "Accuracy", "Bằng chứng nào kiểm chứng được?"], ["P", "Purpose", "Mục đích và thiên kiến là gì?"]];

export default function Home() {
  return <main className={styles.page}>
    <header className={styles.nav}><Link href="/" className={styles.brand}>Chính kiến số.</Link><nav aria-label="Điều hướng chính"><a href="#cach-lam">Cách kiểm tra</a><a href="#co-so">Cơ sở học thuật</a><a href="#thu-nghiem">Kiểm thử</a><a href="#kiem-chung">Kiểm chứng AI</a></nav></header>
    <section className={styles.hero} aria-labelledby="hero-title"><p className={styles.kicker}>Công cụ học tập về liêm chính học thuật</p><h1 id="hero-title">AI trả lời nhanh.<br />Người học cần kiểm tra kỹ.</h1><p className={styles.lead}>Dán đầu ra của một AI để phân tích luận điểm, tìm nguồn đối chiếu và tự đưa ra kết luận có trách nhiệm.</p><a href="#kiem-chung" className={styles.primaryCta}>Bắt đầu kiểm chứng <ArrowRight size={18} /></a></section>
    <section id="cach-lam" className={styles.section}><p className={styles.kicker}>Khung trả lời của advisor</p><h2>SIFT giúp AI đi đúng trọng tâm.</h2><p className={styles.copy}>Mỗi lần phân tích đều theo bốn bước. AI không được phép biến suy đoán thành sự thật.</p><div className={styles.frameworkGrid}>{framework.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={`${styles.section} ${styles.criterionSection}`}><div><p className={styles.kicker}>Tiêu chí đánh giá</p><h2>CRAAP biến kết quả thành các câu hỏi cụ thể.</h2></div><ol className={styles.craapList}>{craap.map(([letter, name, question], index) => <li key={`${letter}-${index}`}><b>{letter}</b><div><strong>{name}</strong><p>{question}</p></div></li>)}</ol></section>
    <section id="co-so" className={styles.section}><p className={styles.kicker}>Vận dụng Tư tưởng Hồ Chí Minh</p><h2>Kiểm tra là một hành vi đạo đức hằng ngày.</h2><div className={styles.principles}><article><ShieldCheck aria-hidden="true" /><h3>Liêm</h3><p>Liêm là trong sạch, không tham lam. Trong học tập với AI, nhóm vận dụng thành việc không nhận phần AI tạo ra là hiểu biết của mình, đồng thời dẫn nguồn và ghi nhận công cụ đã dùng.</p></article><article><SearchCheck aria-hidden="true" /><h3>Chính</h3><p>Chính là không tà, thẳng thắn, đứng đắn. Vì vậy cần thẳng thắn với mức độ hiểu biết và không dùng nội dung chưa kiểm chứng để gây ảnh hưởng.</p></article><article><BookOpenCheck aria-hidden="true" /><h3>Tu dưỡng suốt đời</h3><p>Kiểm chứng cần được lặp lại trước khi nộp bài hoặc chia sẻ thông tin, kể cả khi kết quả AI nghe rất hợp lý. Đây là cách nhóm liên hệ việc tự giác rèn luyện hằng ngày.</p></article></div><p className={styles.sourceNote}>Nguồn học thuật: Bộ Giáo dục và Đào tạo, Giáo trình Tư tưởng Hồ Chí Minh dành cho bậc đại học không chuyên ngành lý luận chính trị, Hà Nội, 2019, Chương 6: “Cần, kiệm, liêm, chính, chí công vô tư” (tr. 130-132); “Tu dưỡng đạo đức suốt đời” (tr. 138). Phần liên hệ với việc dùng AI là diễn giải của nhóm từ các nguyên tắc này.</p></section>
    <section id="kiem-chung" className={`${styles.section} ${styles.advisor}`}><div className={styles.advisorIntro}><p className={styles.kicker}>Thử công cụ</p><h2>Kiểm tra đầu ra AI của bạn.</h2><p>Advisor dùng SIFT để xác định điểm cần chứng minh, dùng CRAAP để đặt câu hỏi về chất lượng nguồn, rồi mới đưa ra nhận định tạm thời.</p></div><AdvisorTool /></section>
    <section id="thu-nghiem" className={styles.section}><p className={styles.kicker}>Kiểm thử và cải tiến</p><h2>Không thay dữ liệu thật bằng con số đẹp.</h2><div className={styles.testGrid}><article><ClipboardCheck aria-hidden="true" /><h3>Mẫu khảo sát 20 sinh viên</h3><p>Ghi thời gian hoàn thành, mức dễ hiểu của SIFT-CRAAP, chất lượng nguồn và góp ý mở sau mỗi lần dùng.</p></article><article><h3>Nhật ký cải tiến</h3><p>Ghi rõ phản hồi, quyết định chỉnh sửa, ngày áp dụng và kết quả kiểm thử lại. Chỉ công bố số liệu sau khi đã thu thập.</p></article></div></section>
  </main>;
}
